server:
    port: 9000
    servlet:
        context-path: "/user"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
  jpa:
    hibernate:
        ddl-auto: create